[tool.ruff]
line-length = 79
lint.select = ["F", "E", "W", "I"]

[tool.black]
line-length = 79

[tool.mypy]
ignore_missing_imports = true

[tool.coverage.run]
omit = [
    "**/piccolo_migrations/*",
    "**/piccolo_app.py",
]
